/* empty css                      */import{S as f,N as g,P as h}from"./assets/vendor-BSBkFbx1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&l(r)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();f.use([g,h]);function w(s){if(!s)return;s.destroy(!0,!0);const e=s.el;e==null||e.removeAttribute("style");const i=e==null?void 0:e.querySelector(".swiper-wrapper");i==null||i.removeAttribute("style"),e==null||e.querySelectorAll(".swiper-slide").forEach(l=>{l.removeAttribute("style")})}function m({rootSelector:s,prevEl:e,nextEl:i,paginationEl:l}){const t=document.querySelector(s);if(!t)return;const o=t.querySelector(".swiper");if(!o)return;let r=null;const n=window.matchMedia("(min-width: 1440px)"),c=()=>{r||(r=new f(o,{slidesPerView:1,spaceBetween:16,speed:450,loop:!1,grabCursor:!0,navigation:{prevEl:e,nextEl:i},pagination:{el:l,clickable:!0,type:"bullets"}}))},a=()=>{r&&(w(r),r=null)},d=()=>{n.matches?a():c()};d();const u=()=>d();n.addEventListener?n.addEventListener("change",u):n.addListener(u)}m({rootSelector:".connect-swiper",prevEl:".connect-prev",nextEl:".connect-next",paginationEl:".connect-pagination"});m({rootSelector:".design-swiper",prevEl:".design-prev",nextEl:".design-next",paginationEl:".design-pagination"});document.querySelectorAll(".faq-acc-el-trigger").forEach(s=>{s.addEventListener("click",()=>{const e=s.closest(".faq-acc-el"),i=e.querySelector(".faq-acc-el-descr-frame"),l=s.querySelector("svg"),t=e.classList.contains("open"),o=`
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 6L8 10L12 6" stroke="#94A3B8" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,r=`
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12 10L8 6L4 10" stroke="#00FFEA" stroke-width="1.33333" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;t?(e.classList.remove("open"),i.style.maxHeight="0",l.outerHTML=o):(e.classList.add("open"),i.style.maxHeight=i.scrollHeight+"px",l.outerHTML=r)})});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),e=s.querySelector(".icon"),i=document.querySelector(".modal"),l=document.querySelectorAll(".menu-list-item"),t=document.querySelector(".header");let o=!1;const r=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 6H20M4 12H20M4 18H20" stroke="#CAD5E2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,n=`
<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M30 30L6 6M30 6L6 30" stroke="white" stroke-opacity="0.7" stroke-width="2" stroke-linecap="round" />
</svg>
    `;s.addEventListener("click",()=>{o=!o,e.innerHTML=o?n:r,o?c():a()}),l.forEach(u=>u.addEventListener("click",()=>{a(),e.innerHTML=r,o=!1})),window.addEventListener("scroll",d);function c(){i.style.display="block"}function a(){i.style.display="none"}function d(){t&&(window.scrollY>60?t.classList.add("header-scroll"):t.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function e(n){const c=document.getElementById(n);if(!c)return;const a=s(),d=c.getBoundingClientRect().top+window.pageYOffset-a;window.scrollTo({top:d,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(c){const a=this.getAttribute("href");if(!a)return;const[d,u]=a.split("#");if(!u)return;const p=window.location.pathname.split("/").pop();!(d===""||d==="./"||d===p||d==="./"+p)||!document.getElementById(u)||(c.preventDefault(),e(u),o(u))})});const l=document.querySelectorAll("section[id]"),t=document.querySelectorAll(".navigation-item");function o(n){t.forEach(a=>a.classList.remove("active"));const c=document.querySelector(`.navigation-item a[href*="#${n}"]`);c&&c.closest(".navigation-item").classList.add("active")}function r(){const n=window.pageYOffset+s()+100;l.forEach(c=>{const a=c.offsetTop,d=a+c.offsetHeight;n>=a&&n<d&&o(c.id)})}if(window.addEventListener("scroll",r),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{e(n),o(n)},300)}});document.addEventListener("DOMContentLoaded",function(){const s=document.getElementById("cookie-popup"),e=document.getElementById("accept-cookies"),i=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(s.style.display="block"),e.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),s.style.display="none"}),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),s.style.display="none"})});
//# sourceMappingURL=index.js.map
